---
- name: Deploy App
  hosts: app
  tasks:
    - name: Fetch the last version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: restart puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      notify: restart puma

  handlers:
  - name: restart puma
    systemd: name=puma state=restarted
